approvalRules:
  - changedFiles:
      allowed:
        - package.json
        - yarn.lock
    properties:
      - files: 
          - package.json
        allowed:
          - dependencies
          - devDependencies
    versionBump:
      packageManager: npm
      versionBumpType: minor
