version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
